# Generated by Django 4.2.30 on 2026-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_coupon_booking_is_scanned_offer_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('THEATRE_ADMIN', 'Theatre Admin'), ('USER', 'Regular User')], default='USER', max_length=20),
        ),
    ]
