# Generated by Django 4.2.30 on 2026-06-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_booking_id_booking_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanlog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='api.booking'),
        ),
    ]
